govuk-one-login/ipv-cri-bav-front

.github/CODEOWNERS, .github/dependabot.yml, .github/pull_request_template.md, .gitignore, .pre-commit-config.yaml, .pre-commit-search-and-replace.yaml
- Created a new repository for BAV CRI. 
- Set up initial configuration for the BAV CRI frontend.
=> KIWI-1253:Initial configuration for BAV CRI frontend

.env.sample, src/app.js, template.yaml
Set log level to WARN in non dev
https://govukverify.atlassian.net/browse/INCIDEN-518
=> KIWI-1403: Updates log level

.github/workflows/post-merge-push-test-container-to-build.yml, .github/workflows/post-merge-push-test-container-to-dev.yml
Create github workflow to create container images on BAV CRI Frontend
Added workflow for the dev and build environment.
Added github secrets to run the workflow
To create container images on the workflow and push it into ECR
- [KIWI-1417](https://govukverify.atlassian.net/browse/KIWI-1417)
[KIWI-1417]: https://govukverify.atlassian.net/browse/KIWI-1417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1417: Create workflow for front test container images

.github/workflows/pull-request-sonar.yml, sonar-project.properties
- Create a BAV CRI API workspace on sonar cloud
- Add SONAR_TOKEN on github repo secrets
- Create properties and workflows for sonar
- [KIWI-1262](https://govukverify.atlassian.net/browse/KIWI-1262)
[KIWI-1262]: https://govukverify.atlassian.net/browse/KIWI-1262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1262: Add Sonar test on BAV CRI Front

.github/workflows/checks.yml, .github/workflows/post-merge-checks.yml, package.json, test/browser/features/HappyPath/BAVAccountDetailsPage.feature
Updating package.json QA Scripts to. resolve issues with GitHub Actions test runs
Updating package.json QA Scripts to. resolve issues with GitHub Actions test runs
GitHub Actions test runs currently failing
- [KIWI-1442](https://govukverify.atlassian.net/browse/KIWI-144)
[KIWI-1442]: https://govukverify.atlassian.net/browse/KIWI-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating package.json QA scripts

test/browser/features/HappyPath/BAVCheckYourDetailsPage.feature, test/browser/features/UnHappyPath/BAVUnhappyCheckYourDetails.feature, test/browser/pages/accountDetailsEditPage.js, test/browser/pages/confirmDetailsPage.js, test/browser/pages/index.js, test/browser/pages/loadBankDetailsPage.js, test/browser/step_definitions/BAVCheckYourDetailSteps.step.js
Added Happy and UnHappy Path tests for the Check Your Details screen
Added  2 new pages, 2 feature files and  a step definition file
To support the happy and unhappy path tests for the Check Your Details screen
KIWI-1336](https://govukverify.atlassian.net/browse/KIWI-1336)
- [x ] Added screenshots to show the implementation is working
=> KIWI-BAV-1336  Happy & Unhappy Path tests for CYA

test/browser/features/HappyPath/BAVNotFoundPage.feature, test/browser/pages/index.js, test/browser/pages/notFoundPage.js, test/browser/step_definitions/BAVNotFoundPageSteps.step.js
QA Updates for KIWI-1408
Test Not Found Page delivered as part of KIWI-1408
- [KIWI-1408](https://govukverify.atlassian.net/browse/KIWI-1408)
[KIWI-1408]: https://govukverify.atlassian.net/browse/KIWI-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1408 QA Updates

package.json, src/locales/cy/pages.errors.yml, src/locales/en/pages.errors.yml, src/views/errors/page-not-found.html, yarn.lock
Adds not found page
- [KIWI-1408](https://govukverify.atlassian.net/browse/KIWI-1408)
[KIWI-1408]: https://govukverify.atlassian.net/browse/KIWI-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1408: Adds not found page

test/browser/features/HappyPath/BAVEscapeChoicePage.feature, test/browser/features/HappyPath/BAVLandingPage.feature, test/browser/features/UnHappyPath/BAVUnhappyCheckYourDetails.feature, test/browser/features/UnHappyPath/BAVUnhappyEscapeChoice.feature, test/browser/pages/confirmDetailsPage.js, test/browser/pages/escapeChoicePage.js, test/browser/pages/index.js, test/browser/pages/landingPage.js, test/browser/step_definitions/BAVCheckYourDetailSteps.step.js, test/browser/step_definitions/BAVEscapeChoiceSteps.step.js, test/browser/step_definitions/BAVLandingPageSteps.step.js
QA Updates for KIWI-1429
Escape Choice Screens delivered as part of KIWI-1429
- [KIWI-1429](https://govukverify.atlassian.net/browse/KIWI-1429)
[KIWI-1429]: https://govukverify.atlassian.net/browse/KIWI-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1429 QA Updates

src/app.js, src/app/bav/steps.js, src/assets/scss/application.scss, src/lib/config.js, src/locales/cy/pages.errors.yml, src/locales/en/pages.errors.yml, src/views/bav/error.html, src/views/errors/error.html
Adds generic error page
- [KIWI-1409](https://govukverify.atlassian.net/browse/KIWI-1409)
[KIWI-1409]: https://govukverify.atlassian.net/browse/KIWI-1409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1409: Adds error page

test/browser/features/HappyPath/BAVErrorPage.feature, test/browser/pages/errorPage.js, test/browser/pages/index.js, test/browser/step_definitions/BAVErrorPageSteps.step.js
QA Updates for KIWI-1409
Test Error Page delivered as part of KIWI-1408
- [KIWI-1409](https://govukverify.atlassian.net/browse/KIWI-1409)
[KIWI-1409]: https://govukverify.atlassian.net/browse/KIWI-1409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1409 QA Updates

test/browser/features/HappyPath/BAVCheckYourDetailsPage.feature, test/browser/pages/accountDetailsEditPage.js, test/browser/pages/confirmDetailsPage.js, test/browser/step_definitions/BAVAccountDetailsSteps.step.js, test/browser/step_definitions/BAVCheckYourDetailSteps.step.js, test/browser/step_definitions/BAVLandingPageSteps.step.js
Added checks that check value and format of amended sort code
KIWI BAV 1336 Additional checks added to test
Parametised the data in the feature file and updated the amend sort code function
Change was made to ensure full code coverage
KIWI-1336(https://govukverify.atlassian.net/browse/KIWI-1336)
- [ X] Added screenshots to show the implementation is working
NA
=> KIWI BAV 1336 Additional checks added to test

.github/workflows/post-merge-push-test-container-to-dev.yml, Dockerfile.test, run-tests-locally.sh, run-tests.sh
Adds run-tests Scripts for BAV FE
=> [KIWI-1441] - Add run-tests scripts

README.md, package.json, src/app/bav/controllers/root.js, src/app/bav/controllers/root.test.js, src/lib/config.js, yarn.lock
Added FE call to `/person-info` and `/person-info-key` endpoints in order to retrieve and decrypt person name values for display in the FE.
[KIWI-1493](https://govukverify.atlassian.net/browse/KIWI-1493)
[KIWI-1493]: https://govukverify.atlassian.net/browse/KIWI-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1493] - BAV | FE | Show Full Name in Check Your Details Screen

test/browser/features/HappyPath/BAVAccountDetailsFailOne.feature, test/browser/features/UnHappyPath/BAVUnhappyAccountDetailsFailOne.feature, test/browser/pages/failOnePage.js, test/browser/pages/index.js, test/browser/pages/relyingPartyPage.js, test/browser/step_definitions/BAVCheckYourDetailSteps.step.js, test/browser/step_definitions/details.js, test/browser/support/env.js, test/browser/support/setup.js, test/browser/support/shared_claim.json, test/browser/support/shared_claim_nigel.json
Added front-end automation tests for the Fail 1 screen.
- [KIWI-1338](https://govukverify.atlassian.net/browse/KIWI-1338)
[KIWI-1338]: https://govukverify.atlassian.net/browse/KIWI-1338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI 1338 QA

test/browser/features/HappyPath/BAVCheckYourDetailsPage.feature, test/browser/pages/confirmDetailsPage.js, test/browser/step_definitions/BAVCheckYourDetailSteps.step.js, test/browser/support/shared_claim.json
Added the automation tests for verifying that the users full name is displayed in the Check Your Details screen.
- [KIWI-1493](https://govukverify.atlassian.net/browse/KIWI-1493)
[KIWI-1493]: https://govukverify.atlassian.net/browse/KIWI-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1493] QA

.github/workflows/checks.yml, .github/workflows/pull-request-sonar.yml, package.json, src/app/bav/controllers/nameInfo.js, src/app/bav/controllers/nameInfo.test.js, src/app/bav/controllers/root.js, src/app/bav/controllers/root.test.js, src/app/bav/steps.js, src/lib/config.js
Creates /name-info route to fetch the details
Using root controller was causing an infinite loop
- [KIWI-1568](https://govukverify.atlassian.net/browse/KIWI-1568)
[KIWI-1568]: https://govukverify.atlassian.net/browse/KIWI-1568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1568: creates /name-info route

src/views/bav/check-details.html, src/views/bav/could-not-match-bank.html, src/views/bav/enter-account-details.html, src/views/bav/how-continue-bank.html, test/browser/features/HappyPath/BAVCheckYourDetailsPage.feature, test/browser/pages/landingPage.js
Adjust test to incorporate the copy modification.
- [KIWI-1401](https://govukverify.atlassian.net/browse/KIWI-1401)
[KIWI-1401]: https://govukverify.atlassian.net/browse/KIWI-1401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1401-QA -update copy on test

.pre-commit-config.yaml, README.md
- Updated pre-commit hooks with `pre-commit autoupdate`
- Added instructions for how to use pre-commit in readme.md
- Pre-commits to be used across Identity repos
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-486: Update pre-commit hooks and readme

.github/workflows/checks.yml, .github/workflows/post-merge-checks.yml, package.json, run-tests.sh, test/browser/features/E2E/BAVEndToEnd.feature, test/browser/step_definitions/BAVBackendValidation.step.js, test/browser/support/BAV_COP_REQUEST_SENT_SCHEMA.json, test/browser/support/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json, test/browser/support/BAV_CRI_END_SCHEMA.json, test/browser/support/BAV_CRI_START_SCHEMA.json, test/browser/support/BAV_CRI_VC_ISSUED_SCHEMA.json, test/browser/support/TestHarness.js
E2E test added to FE BAV repo
Additional coverage in regression runs 
- [KIWI-1672](https://govukverify.atlassian.net/browse/KIWI-1672)
[KIWI-1627]: https://govukverify.atlassian.net/browse/KIWI-1627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-1672]: https://govukverify.atlassian.net/browse/KIWI-1672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1672 QA Updates

check-logs.sh, run-tests-locally.sh
- Adds auth env vars to run-tests-locally
- Updates PII script after https://github.com/govuk-one-login/ipv-cri-bav-front/pull/164
To run tests locally
=> Updates run-tests-locally and check-logs scripts

package.json, src/app.js, yarn.lock
Add new TXMA AUDIT ENCODED header into axios request
- Install new package One Login common headers (https://www.npmjs.com/package/one-login-common-headers?activeTab=readme)
- add new axios interceptor
- https://govukverify.atlassian.net/browse/DCP-3162
=> add txma audit encoded header

.github/workflows/pre-merge-checks.yml
Re-add the browser tests step
WAF issue has been fixed so these should now pass
1st attempt pre WAF change and 3 successful runs post change
- [KIWI-KIWI-1617](https://govukverify.atlassian.net/browse/KIWI-KIWI-1617)
=> KIWI-1617: Re-add the browser tests step

template.yaml
Cloud front Pilot
Add new DNS Record
To add new DNS record pointing to cloud front
- [PLAT-4023](https://govukverify.atlassian.net/browse/PLAT-4023)
[PLAT-4023]: https://govukverify.atlassian.net/browse/PLAT-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-4023: Cloudfront Pilot on BAV CRI

test/browser/features/E2E/BAVEndToEnd.feature
Update E2E tag for BAV test
Current E2E tag not included in e2e:cd pipeline test run script
N/A
=> Update test tag for BAV E2E Test

.secrets.baseline, template.yaml
Fix the template file changes to check the build environment condition
Changed the condition to check build environment
Deployment failed on dev and build
- [PLAT-4023](https://govukverify.atlassian.net/browse/PLAT-4023)
[PLAT-4023]: https://govukverify.atlassian.net/browse/PLAT-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-4023: Fix the template file issues

Dockerfile
Start FE in Debug to get more logs from performance runs
=> [KIWI-1767] Start FE in Debug

.secrets.baseline, template.yaml
Add Manual Support URL for the frontend alarms
Implemente alarms for the BAV CRI Frontend
- [IPS-653](https://govukverify.atlassian.net/browse/IPS-653)
- [IPS-678](https://govukverify.atlassian.net/browse/IPS-678)
[IPS-653]: https://govukverify.atlassian.net/browse/IPS-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-678]: https://govukverify.atlassian.net/browse/IPS-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-653: Implement alarm for BAV CRI frontend

test/browser/support/BAV_COP_REQUEST_SENT_SCHEMA.json, test/browser/support/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json, test/browser/support/BAV_CRI_END_SCHEMA.json, test/browser/support/BAV_CRI_START_SCHEMA.json, test/browser/support/BAV_CRI_VC_ISSUED_SCHEMA.json, test/browser/support/TestHarness.js
Remove false positives in FE TxMA Validation Tests
- [KIWI-1773](https://govukverify.atlassian.net/browse/KIWI-1773)
[KIWI-1773]: https://govukverify.atlassian.net/browse/KIWI-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> False positives in FE TxMA Validation Tests

src/views/bav/check-details.html
Add data-test attribute
For end to end tests
=> Add data-test attribute

.secrets.baseline, template.yaml
- Revert the previous changes made for the Cloudfront pilot testing
- Revert all the changes made for the cloudfront pilot
- New changes has come through which require the older versions to revert
- [IPS-708](https://govukverify.atlassian.net/browse/IPS-708)
[IPS-708]: https://govukverify.atlassian.net/browse/IPS-708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-708: Revert the Cloudfront pilot changes

src/views/bav/check-details.html, src/views/bav/enter-account-details.html
- Moved closing div so that it covers whole question not just title
- Removed duplicate row/column classes
- [KIWI-1809](https://govukverify.atlassian.net/browse/KIWI-1809)
[KIWI-1809]: https://govukverify.atlassian.net/browse/KIWI-1809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1809 Move divs

.env.sample, .secrets.baseline, template.yaml, test/browser/support/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json
- DNS changeover to the cloudfront DNS to test the traffic through Cloudfront
- Added the new cloudfront DNS
- Modified Record to test DNS changeover
- Cherry-pick the test changes to add the tests for new DNS
- Test CloudFront DNS on the BAV CRI Build
- [IPS-717](https://govukverify.atlassian.net/browse/IPS-717)
[IPS-717]: https://govukverify.atlassian.net/browse/IPS-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-717: Add DNS changeover to test the CloudFront

package.json, yarn.lock
Upgraded
- common-express to 6.4.0 [release notes](https://github.com/govuk-one-login/ipv-cri-common-express/releases/tag/v6.4.0)
- frontend-passthrough-headers [release notes](https://github.com/govuk-one-login/frontend-passthrough-headers/releases/tag/v1.0.0)
=> Upgrades packages to include latest CF changes

template.yaml
Turns on GA4 in integration and prod. Other values are correct as per https://govukverify.atlassian.net/wiki/spaces/DID/pages/4226809994/GA+4+Package+V1.0.3+Go+No+Go+-+Kiwi
=> Turns on GA4 in integration and prod

template.yaml
Turns on language toggle in prod
=> DCP-3468: Turns on language toggle in prod

template.yaml
- Due to load balancer changing names, configuring the waf association on the frontend.
- Add Cloudfront WAF association on the frontend
- Load balancer name changes on every frontend deployment which makes it difficult to configure the waf association.
- [IPS-733](https://govukverify.atlassian.net/browse/IPS-733)
[IPS-733]: https://govukverify.atlassian.net/browse/IPS-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-733: Create WAF association on the frontend template

.github/workflows/post-merge-actions-build.yml, .github/workflows/post-merge-actions-dev.yml
- Update upload action ECR version from v1.2.1 to v1.2.4
- Update upload action ECR version from v1.2.1 to v1.2.4
- [IPS-814](https://govukverify.atlassian.net/browse/IPS-814)
[IPS-814]: https://govukverify.atlassian.net/browse/IPS-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-814: Update Upload action ECR version

test/browser/support/BAV_CRI_VC_ISSUED_SCHEMA.json, test/browser/support/BAV_EXPERIAN_REQUEST_SENT_SCHEMA.json
Updated the audit events to align with api
To enable tests to pass in the pipeline
=> KIWI-2070: Updated audit events to align with the BAV API changes

.secrets.baseline, Dockerfile, template.yaml
- Configured AWS ECS healthchecks in template
- Updated Dockerfile to reference healthcheck
=> KIWI-2135 - Configuring ECS Healthchecks

package.json, src/app.js, src/lib/overload-protection-config.js
Implemented overload protection to return 503s from the FE when event loop delay exceeds threshold indicating node app is overloaded
=> KIWI-2010 - Implementing oveload protection

run-tests.sh, test/browser/pages/relyingPartyPage.js, test/browser/step_definitions/BAVBackendValidation.step.js
Updates to /token logic in E2E tests following /token core consumption BE work being merged
- [KIWI-2302](https://govukverify.atlassian.net/browse/KIWI-2302)
[KIWI-2303]: https://govukverify.atlassian.net/browse/KIWI-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-2302]: https://govukverify.atlassian.net/browse/KIWI-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2302: Updates to /token endpoint logic

yarn.lock
frontend-ui v1.3.12 installed
To remove query parameter being appended to Contact Us link - potential for Contact Centre to paste the link and use it to start a session
- [KIWI-2418](https://govukverify.atlassian.net/browse/KIWI-2418)
Uploading Screen Recording 2025-07-29 at 10.25.33.mov…
[KIWI-2418]: https://govukverify.atlassian.net/browse/KIWI-2418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2418] - | FE | Contact Us link appends the full URL 

template.yaml
Switched on the Rebrand feature flag in Production
Introducing brand changes
- [KIWI-2374](https://govukverify.atlassian.net/browse/KIWI-2374)
[KIWI-2374]: https://govukverify.atlassian.net/browse/KIWI-2374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2374] - BAV | Enable the Rebrand feature flag in Production
