govuk-one-login/ipv-cri-bav-front

- .github/CODEOWNERS
- Add the CODEOWNERS for new govuk-one-login github BAV Front
- [KIWI-1323](https://govukverify.atlassian.net/browse/KIWI-1323)
[KIWI-1323]: https://govukverify.atlassian.net/browse/KIWI-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1323: Github migration - Post cleanup for Bav CRIi Frontend

- src/app/bav/controllers/accountDetails.js
- src/app/bav/controllers/accountDetails.test.js
- src/app/bav/fields.js
- src/app/bav/steps.js
- src/lib/config.js
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/bav/enter-account-details.html
Add bank account details entry screen to BAV FE
Errors are triggered if either input is empty, or the number of characters does not adhere to the length rules for each input (6 for sort code and 6-8 for account number). Additionally, "dd-dd-dd" and "dd dd dd" are allowed for sort code.
- [KIWI-1233](https://govukverify.atlassian.net/browse/KIWI-1333)
[KIWI-1233]: https://govukverify.atlassian.net/browse/KIWI-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1233] - BAV | FE | Build Account Details Screen

- test/browser/features/HappyPath/BAVAccountDetailsPage.feature
- test/browser/features/UnHappyPath/BAVUnhappyAccountDetails.feature
Pass in data values used in parametised scenario outline
Amended the Scenario Outline header to include the parametised value of the sortCode and accountNumber variables
Adding the variables to the description will make identifying any failures easier as the value used is now in the header
KIWI-BAV-1333 (https://govukverify.atlassian.net/browse/KIWI-BAV-1333)
- [ x ] Added screenshots to show the implementation is working
NA
> KIWI-BAV-1333-TD Scenario data reporting update

- package.json
- test/browser/pages/accountDetailsEditPage.js
- test/browser/pages/accountDetailsPage.js
- test/browser/pages/landingPage.js
Changed the selector used for the error summary box as the ID was removed in [version 4.4 of govuk-components](https://github.com/alphagov/govuk-frontend/compare/v4.3.1...v4.4.1) so it can no longer be used
So that tests are able to find the right element
> Fix failing tests

- src/app/bav/controllers/confirmDetails.js
- src/app/bav/steps.js
- src/app/bav/utils.js
- src/app/bav/utils.test.js
- src/lib/config.js
The backend requires a plain string with no dashes or spaces. This PR formats the sort code before it is submitted.
Also adds done route
Fix validation error
> Formats sort code before submitting

- src/app.js
Passes `authorizationPath` into the `setAPIConfig` function
To fix this error
> Sets authorizationPath correctly

- .github/workflows/post-merge-actions-build.yml
- .github/workflows/post-merge-actions-dev.yml
- Updated post-merge workflow to use devplatform-upload-action-ecr@1.2.0
- Replaced individual SAM/docker steps
- Required for canary deployments across Identity
- [IPS-491](https://govukverify.atlassian.net/browse/IPS-491)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- Successful workflow: https://github.com/govuk-one-login/ipv-cri-bav-front/actions/runs/7786214254
[IPS-491]: https://govukverify.atlassian.net/browse/IPS-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update post-merge workflow to use devplatform-upload-action-ecr@1.2.0

- test/browser/features/UnHappyPath/BAVUnhappyAccountDetailsSecondFail.feature
Created tests for second fail attempt
- [KIWI-1577](https://govukverify.atlassian.net/browse/KIWI-1577)
[KIWI-1577]: https://govukverify.atlassian.net/browse/KIWI-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI -1577] QA - Route Users to IPV Core on Second Fail 

- package.json
- src/locales/cy/fields.yml
- yarn.lock
Upgrade common-express to v5.0.0
https://govukverify.atlassian.net/browse/KIWI-1616?focusedCommentId=124821
> [KIWI-1616] - Upgrade common-express to v5.0.0

- src/app/bav/controllers/confirmDetails.js
- src/app/bav/controllers/confirmDetails.test.js
- src/app/bav/steps.js
- test/browser/features/UnHappyPath/BAVUnhappyAccountDetailsSecondFail.feature
Rename retryCount to attemptCount and reset it on success
To allow push to success when user has 1 fail and 1 pass and 2 fails
- [KIWI-1577](https://govukverify.atlassian.net/browse/KIWI-1577)
[KIWI-1577]: https://govukverify.atlassian.net/browse/KIWI-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1577: Rename retryCount to attemptCount and reset it on success

- src/locales/cy/default.yml
- src/locales/en/default.yml
Added empty quote in English and Welsh default yaml files to remove error showing govuk.serviceName in screen title tag
Bug fix
- [KIWI-1664](https://govukverify.atlassian.net/browse/KIWI-1664)
[KIWI-1664]: https://govukverify.atlassian.net/browse/KIWI-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1664]- BAV | FE | Incorrect tab title on all pages

- run-tests.sh
- template.yaml
Update template.yml to return correct test harness url in cloud formation template
E2E tests added to BAV FE repo require correct test harness URL for BE validation logic
- [KIWI-1672](https://govukverify.atlassian.net/browse/KIWI-1672)
[KIWI-1672]: https://govukverify.atlassian.net/browse/KIWI-1672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updating template to return correct testHarness URL

- template.yaml
Add ECS step scaling policy and alarms following https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/3834744807/ADR+0140+Fargate+Scaling
Created the following resources:
-  StepScaleOutPolicy
- StepScaleInPolicy
- StepScaleOutAlarm
- StepScaleInAlarm
Align task scaling with CoreFront and orange/lime configurations
- [IPS-161](https://govukverify.atlassian.net/browse/IPS-161)
- [IPS-476](https://govukverify.atlassian.net/browse/IPS-476)
[IPS-161]: https://govukverify.atlassian.net/browse/IPS-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-476]: https://govukverify.atlassian.net/browse/IPS-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [IPS-476]: Add ECS step scaling policy and alarms

- .secrets.baseline
- template.yaml
- Add CSLS subscription filter for the spunk onboarding. 
- Modified CSLS Egress stub 2
- Enabled the CSLS filter subscription as splunk onboarding started
- BAV Accounts are added on the CSLS accounts which allows to push log groups
- For onboarding BAV CRI logs into splunk
- [KIWI-1308](https://govukverify.atlassian.net/browse/KIWI-1308)
[KIWI-1308]: https://govukverify.atlassian.net/browse/KIWI-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1308: Add CSLS subscrptions for Splunk Onboarding

- .github/workflows/pre-merge-checks.yml
Browser tests running pre-merge is causing intermittent unknown failures, whilst investigation for this is underway this PR temp removes browser testing from our pre-merge workflow
> Remove Browser Tests

- src/locales/en/fields.yml
Adds prefix values to fileds.yml to fix UI break with the latest package upgrades
Ticket: https://govukverify.atlassian.net/browse/KIWI-1710
> [KIWI-1710] Add prefix to SC AN fields

- run-tests.sh
- template.yaml
…sting
Update template.yml to output the pretty stub URL for use in testing 
URL currently used for IPV_STUB_URL is https://vw5cq9hzu6.execute-api.eu-west-2.amazonaws.com/dev/ and we need this returned in pretty format for use in IPV Core handoff testing
> Use IPV Pretty Stub URL for IPV Core handoff testing

- src/app.js
- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/pages.yml
Updated BAV journey to include Welsh translation for all text.
So Welsh speaking users can access the BAV service.
- [KIWI-1540](https://govukverify.atlassian.net/browse/KIWI-1540)
[KIWI-1540]: https://govukverify.atlassian.net/browse/KIWI-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1540] - BAV | FE | Welsh Translation copy changes

- src/locales/cy/pages.yml
Translated warning label on escape choice screen as work for label had been done in previous ticket 
So Welsh speakers can read the warning label
- [KIWI-1607](https://govukverify.atlassian.net/browse/KIWI-1607)
[KIWI-1607]: https://govukverify.atlassian.net/browse/KIWI-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1607] -BAV | FE | Add warning to escape choice screen

- .pre-commit-config.yaml
- .secrets.baseline
- template.yaml
Test the Cloudfront pilot on the build environment. Test the DNS pointing to Cloudfront
- Set the DNS name pointing to Cloudfront in the build environment
- Having tested the hostname pointing to Cloudfront manually, set up the DNS pointing to cloud front on the build environment only
Test the cloud front pilot on the build environment
- [PLAT-4023](https://govukverify.atlassian.net/browse/PLAT-4023)
[PLAT-4023]: https://govukverify.atlassian.net/browse/PLAT-4023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLAT-4023: Add DNS name pointing to Cloud Front on the build environment

- package.json
- src/app.js
- src/app/bav/controllers/abort.js
- src/app/bav/controllers/abort.test.js
- src/app/bav/controllers/checkDetails.js
- src/app/bav/controllers/checkDetails.test.js
- src/app/bav/controllers/nameInfo.js
- src/app/bav/controllers/nameInfo.test.js
- test/utils/test-helpers.js
- yarn.lock
Refactor `txma-audit-encoded` header based on latest updates / documentation.
This removes the old `one-login-common-headers` package which has been deprecated based on ADR comments here: https://github.com/govuk-one-login/architecture/pull/666/files#r1539306758.
This adds the new `@govuk-one-login/frontend-passthrough-headers` package, and adds the headers for each internal request. The new package is used to abstract the header name out of each repo, and provide a warning in the name around the Personal Data element of the headers.
I have also added the `txma-audit-encoded` header in the test requests.
Due to the ADR comment listed above ☝️
- [DFC-559](https://govukverify.atlassian.net/browse/DFC-559)
- [ADR](https://github.com/govuk-one-login/architecture/pull/666)
[DFC-559]: …
> [DFC-559]: Refactor txma header implementation

- package.json
- yarn.lock
Bumps common express from 6.2.0 to 6.2.2
The recent GA4 package release had to be updated in common-express as well. Bumping this version will produce cleaner logs
> BAU: Bump di-ipv-cri-common-express 6.2.0 to 6.2.2

- .env.sample
- test/browser/support/BAV_COP_RESPONSE_RECEIVED_SCHEMA.json
Updates tests to expect device_information in txma event
To allow testing of cloudfront work
e2e tests passing against build env
> Updates tests to expect device_information in txma event

- src/assets/scss/application.scss
Changed width of error summary component
To align with GOV UK design system
- [KIWI-1798](https://govukverify.atlassian.net/browse/KIWI-1798)
[KIWI-1798]: https://govukverify.atlassian.net/browse/KIWI-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1798] - Remove the width limit on the error summary component

- package.json
- src/app/bav/controllers/abort.js
- src/app/bav/controllers/checkDetails.js
- src/app/bav/controllers/nameInfo.js
- yarn.lock
- Bumped the version of @govuk-one-login/frontend-passthrough-headers
- Added the new url parameter asked by the new version of createPersonalDataHeaders
- The function is outputing an additional header x-forwarded-for.
- Added more logs.
- [DFC-567](https://govukverify.atlassian.net/browse/DFC-567)
[DFC-567]: https://govukverify.atlassian.net/browse/DFC-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bump frontend-passthrough-headers version and add new url parameter

- template.yaml
- Remove the WAF association before deploy cloudfront WAF
- Removed the WAF Association with the load balancer.
- This is to deploy the cloudfront and WAF global deployment
- The WAF Association is removed to add the Global WAF to test Cloudfront
- Existing WAF will create a drift if association created on the global WAF
- [IPS-715](https://govukverify.atlassian.net/browse/IPS-715)
[IPS-715]: https://govukverify.atlassian.net/browse/IPS-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-715: Remove WAF Association from the frontend for cloudfront

- .secrets.baseline
- template.yaml
- Due to latest changes from dev platform,  the dev environment could not be used as a test bed for the cloudfront.
- Deployed the latest stacks on the build, staging and integration
- Configured the build and staging envirnonent.
- Based on the test reports from the build and staging, cloudfront could be deployed on the integration and production
- Redeploy the cloudfront stacks due to the new changes on dev platform
- Deployed on the dev environment and added the screenshot of test report
- Deployed the new changes on build, staging and integration
- Enabled the DNS switchover on dev, build, staging and integration
- Recent changes on the cloudfront distribution template.
- [IPS-689](https://govukverify.atlassian.net/browse/IPS-689)
[IPS-689]: …
> IPS-689: Cloudfront DNS changeover on BAV build and staging environments

- src/app.js
Use correct var for ANALYTICS_COOKIE_DOMAIN
Was breaking language cookie persistence
- [KIWI-1852](https://govukverify.atlassian.net/browse/KIWI-1852)
[KIWI-1852]: https://govukverify.atlassian.net/browse/KIWI-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1852 Use correct ANALYTICS_COOKIE_DOMAIN

- test/browser/support/BAV_COP_REQUEST_SENT_SCHEMA.json
- test/browser/support/BAV_CRI_SESSION_ABORTED_SCHEMA.json
- test/browser/support/BAV_CRI_START_SCHEMA.json
Update following TxMA JSON Schema to check for `restricted.device_information` field
- BAV_COP_REQUEST_SENT_SCHEMA.json
- BAV_CRI_SESSION_ABORTED_SCHEMA.json
- BAV_CRI_START_SCHEMA.json
Support testing of CloudFront changes
- [KIWI-1868](https://govukverify.atlassian.net/browse/KIWI-1868)
[KIWI-1868]: https://govukverify.atlassian.net/browse/KIWI-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1868 - Cloudfront Header Updates

- package.json
- yarn.lock
Bump `@govuk-one-login/frontend-analytics` to v2.0.1
Request from FEC to upgrade due to a new release they’ve made to fix a bug they discovered
- [KIWI-1912](https://govukverify.atlassian.net/browse/KIWI-1912)
[KIWI-1912]: https://govukverify.atlassian.net/browse/KIWI-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Kiwi | FE | Upgrade to frontend-analytics version 2.0.1

- .secrets.baseline
- template.yaml
Stage 1 of 2 for enabling ECS Canaries (Stage 2 is [here](https://github.com/govuk-one-login/ipv-cri-bav-front/pull/313))
Added the ECSCanaryDeployment nested Stack to handle Blue/Green ECS deployments
Assumption made that we will always want to have Canary infrastructure in place (even if deployment strategy is AllAtOnce)
Canary deployments provide extra safety measures when rolling out new application image versions
- [IPS-558](https://govukverify.atlassian.net/browse/IPS-558)
[IPS-558]: https://govukverify.atlassian.net/browse/IPS-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-558 stage1 adding ecs canary stack, target group and alarms

- .secrets.baseline
- template.yaml
Stage 2 of 2 for enabling ECS Canaries (Stage 1 is [here](https://github.com/govuk-one-login/ipv-cri-bav-front/pull/311))
This is a fairly arbitrary change to trigger the deployment process, but removes some now-unused ECS config.
Canary deployments provide extra safety measures when rolling out new application image versions
- [IPS-558](https://govukverify.atlassian.net/browse/IPS-558)
[IPS-558]: https://govukverify.atlassian.net/browse/IPS-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ips 558 canary stage2

- template.yaml
BAVFrontEcsService dimension removed from FELowContainerTaskCountAlarm and FELowContainerTaskCountCriticalAlarm
During canary deployment FELowContainerTaskCountCriticalAlarm critical alarm triggered as the alarm includes BAVFrontEcsService. When switching from ecs to code deploy, the target group is switched hence triggering the alarm
- [IPS-1003](https://govukverify.atlassian.net/browse/IPS-1003)
[IPS-1003]: https://govukverify.atlassian.net/browse/IPS-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [IPS-1003]-container task count alarm ecs service removed

- .secrets.baseline
- template.yaml
- Add BAV CRI alarms to the pager duty topic. This will publish on the topic when the alarm is triggered and pager duty will be triggered.
- Add BAV CRI alarms to the pager duty topic to publish the topic
- Add BAV CRI alarms to the pager duty topic to publish the topic
- [IPS-1181](https://govukverify.atlassian.net/browse/IPS-1181)
[IPS-1181]: https://govukverify.atlassian.net/browse/IPS-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1181: Subscribe BAV CRI alarms to the pager duty topic

- template.yaml
- changed conditions on the pager duty alarms to. avoid dev environment.
- Pager duty topics are not deployed on the dev environment
- changed conditions on the pager duty alarms to. avoid dev environment.
- Pager duty topics are not deployed on the dev environment
- changed conditions on the pager duty alarms to. avoid dev environment.
- Pager duty topics are not deployed on the dev environment
- [IPS-1181](https://govukverify.atlassian.net/browse/IPS-1181)
[IPS-1181]: https://govukverify.atlassian.net/browse/IPS-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1181: change condition to avoid the pager duty alarms on dev env

- src/app.js
- src/lib/config.js
Added name to hmpo-logger.get() function to prevent use of sync API which blocks event loop
> KIWI-2012 - Adding Package name to hmpo-logger

- package.json
- src/views/bav/cannot-proceed.html
- src/views/bav/check-details.html
- src/views/bav/could-not-match-bank.html
- src/views/bav/enter-account-details.html
- src/views/bav/how-continue-bank.html
- yarn.lock
Upgraded frontend-analytics package version and added missing data attributes used for GA4 navigation tracking
To ensure service is up to date and capturing analytics data correctly
- [KIWI-2216](https://govukverify.atlassian.net/browse/KIWI-2216)
[KIWI-2216]: https://govukverify.atlassian.net/browse/KIWI-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2216] Upgrade FE analytics from v 2.0.1 to 3.1.0

- .secrets.baseline
- template.yaml
- Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
- Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
- Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
- [IPS-1407](https://govukverify.atlassian.net/browse/IPS-1407)
[IPS-1407]: https://govukverify.atlassian.net/browse/IPS-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1407: Migrate WAF in BAV CRI to FMS

- package.json
- yarn.lock
Updated common-express package to latest version which includes fix for device intelligence feature toggle.
- [KIWI-2262](https://govukverify.atlassian.net/browse/KIWI-2262)
[KIWI-2262]: https://govukverify.atlassian.net/browse/KIWI-2262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2262 - Bump common-express version

- template.yaml
Disabled Device Intelligence in Staging env by setting the value of `DEVICEINTELLIGENCEENABLED` env var in CF template to `false`
To unblock IPV core pipelines as referenced [here]([here](https://gds.slack.com/archives/C05HE9FL65S/p1747759982973109?thread_ts=1747756522.823159&cid=C05HE9FL65S))
- [KIWI-2323](https://govukverify.atlassian.net/browse/KIWI-2323)
[KIWI-2323]: https://govukverify.atlassian.net/browse/KIWI-2323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2303 - DI | Turn off Device Intelligence in Staging

- template.yaml
Disabled Device Intelligence in Staging env by setting the value of `DEVICEINTELLIGENCEENABLED` env var in CF template to `false`
To unblock IPV core pipelines as referenced [here]([here](https://gds.slack.com/archives/C05HE9FL65S/p1747759982973109?thread_ts=1747756522.823159&cid=C05HE9FL65S))
- [KIWI-2323](https://govukverify.atlassian.net/browse/KIWI-2323)
[KIWI-2323]: https://govukverify.atlassian.net/browse/KIWI-2323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2323 - DI | Turn off Device Intelligence in Staging

- .secrets.baseline
- src/lib/config.js
- template.yaml
Set device intelligence cookie domain to account.gov.uk across all envs
To address issue with header size stemming from environment specific domain names
- [KIWI-2318](https://govukverify.atlassian.net/browse/KIWI-2318)
[KIWI-2318]: https://govukverify.atlassian.net/browse/KIWI-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2318] - DI | Set Cookie domain for all environments

- package.json
- yarn.lock
Updated express
Updated Jest
Moved some dependencies from dependencies to devDependencies
Replaced references of "GOV.UK Sign In" with "GOV.UK One login" in template file
Removed express-async-errors
To resolve some open alerts and assist dependency management going forward
- [KIWI-2348](https://govukverify.atlassian.net/browse/KIWI-2348)
- [KIWI-2195](https://govukverify.atlassian.net/browse/KIWI-2195)
Tests were run to validate the safe removal of express-async-errors.
- Unit tests: All passed
- Browser tests: All passed 
[KIWI-2348]: https://govukverify.atlassian.net/browse/KIWI-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-2195]: https://govukverify.atlassian.net/browse/KIWI-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
> KIWI-2348: Addressing some outstanding dependabot alerts

- template.yaml
Replaced references of "GOV.UK Sign In" with "GOV.UK One login" in template file
Remove inconsistencies descriptions for BAV FE
- [KIWI-2348](https://govukverify.atlassian.net/browse/KIWI-2348)
- [KIWI-2195](https://govukverify.atlassian.net/browse/KIWI-2195)
[KIWI-2348]: https://govukverify.atlassian.net/browse/KIWI-2348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-2195]: https://govukverify.atlassian.net/browse/KIWI-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2348B] - Update references in template file

- template.yaml
Set the Rebrand feature flag in Integration to true
To align with rebranding and allow for further E2E testing.
- [KIWI-2331](https://govukverify.atlassian.net/browse/KIWI-2331)
[KIWI-2331]: https://govukverify.atlassian.net/browse/KIWI-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2331] - BAV | FE | Enable the Rebrand feature flag in Integration

- src/locales/cy/default.yml
- src/locales/en/default.yml
Remove text fields relating to rebranding in default.yml for both languages
The common-express, which introduces the brand changes holds the default fields for govuk text in both languages, the change is to prevent any risk of overriding or misalignment in the future.
- [KIWI-2347](https://govukverify.atlassian.net/browse/KIWI-2347)
[KIWI-2347]: https://govukverify.atlassian.net/browse/KIWI-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2347] - BAV | FE | Remove text fields relating to footer and banners

- .github/dependabot.yml
Updated dependabot yaml to ignored node 24 in docker file
To ignore node 24 in docker
- [KIWI-2423](https://govukverify.atlassian.net/browse/KIWI-2423)
[KIWI-2423]: https://govukverify.atlassian.net/browse/KIWI-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2423] - Dependabot | Sprint 6 | Update yaml file 
